### ISSUE TITLE
Where is mysql_config?

### ISSUE THREAD

**Issue by canwe** [TablePlus/DBngin#24]
details

1. Driver MySQL 5.7.23

2. DBng build number: 1.0

3. macOS version: 10.14.2

4. The steps to reproduce this issue: create new database service, try to find mysql_config

**Comment by huyphams** [comment]
Hi @canwe which build are you using? 1.0 is the version, not the build number.
Since build 16, DBngin has supported custom user config. And you can select your config file.

There is no default no config file.

<img width="512" alt="screen shot 2019-03-01 at 4 44 07 pm" src="https://user-images.githubusercontent.com/3654622/53629912-4fbf7900-3c41-11e9-93fd-9fa96220a4ae.png">

**Comment by canwe** [comment]
Hi @huyphams 
I just want to know where DBngin store mysql binaries. Where is mysql/bin directory located?

**Comment by huyphams** [comment]
Hi @canwe It’s /User/Shared
