### ISSUE TITLE
Where is my.cnf?

### ISSUE THREAD

**Issue by iam-adty** [TablePlus/DBngin#7]
1. Driver: MySQL 5.7.23
2. DBngin build number: 1.0 (10)
3. macOS version: 10.13.6
4. The steps to reproduce this issue: create new database service
--------------
where is my.cnf? can't find in default path.

**Comment by huyphams** [comment]
It's here:  `/Users/<user_name>/Library/Application\ Support/com.tinyapp.DBngin/Engines/mysql/` I will add a shortcut to navigate to the config file in the next update.

**Comment by iam-adty** [comment]
ok. thanks @huyphams . waiting for the next update.

**Comment by shanke** [comment]
Waiting too. It would be nice to have multiple mysql server with different *.cnf files.

**Comment by shanke** [comment]
Is this feature already on progress?

**Comment by huyphams** [comment]
Yep, we're working on it.

**Comment by shanke** [comment]
Updates concerning this feature?

**Comment by huyphams** [comment]
We will release this feature on build 16 today, thanks

**Comment by colonelclick** [comment]
Where is the shortcut to navigate to my.cnf? I do not find the shortcut.

**Comment by lukepearce** [comment]
If you right click on the MySQL service, you can "Edit" and select a custom `my.cnf` file to use for that server.

![image](https://user-images.githubusercontent.com/1732601/106394470-a5d06480-63f4-11eb-9ea3-e12720448aca.png)

**Comment by abkrim** [comment]
Hi
With DBNgin version 7.2 not show path

![CleanShot 2024-09-13 at 10 32 53](https://github.com/user-attachments/assets/e950ece8-838e-44f1-8c64-3c3bfba9b4fc)

Any idea when can I get information?

**Comment by huyphams** [comment]
You mean the my.cnf @abkrim ?

**Comment by abkrim** [comment]
@huyphams YEs.

I see path for me in ` ~/Library/Application\ Support/com.tinyapp.DBngin/Engines/mysql/9CE8EC55-D812-4F01-9D0D-E9EDCA8400D4/` but I don't know if there is a best place.

Need add some values for restore dumps with others values. 


Thanks.

**Comment by huyphams** [comment]
There is no my.cnf by default. You can create one if you want to customize it.

**Comment by jAKErCZ** [comment]
I have the same problem as @abkrim . Where can I find the configuration file? Or what should the default configuration file look like that I can use for my own solution?

**Comment by colonelclick** [comment]
There is no default file. The default settings are MySQL defaults, which you can find in the docs. If you make a my.cnf file, the only thing you need to put into it are settings that you want to override. If you only want to override one setting, then your file will only be two lines. (One line for the section header.) The file could live anywhere, but it makes sense to store it near the binaries, because it is a convenient location to get to.

This is my own solution that is working well.

- Open DBNgin
- Right click the server
- Select the entry to show the database binaries
- Now you should be in a folder with the files for this version; create your my.cnf here and override any settings you want, as per the syntax in the docs; I like storing the cnf here because you can quickly find it again by repeating the first few steps above
- Go back to the DBNgin interface
- Right click the server again and select edit
- Select the config you just made and save the settings
- Restart the server
- If it fails to start you have a syntax error in the cnf file


By way of example only, this is what my file looks like. This is an example and may not be suitable for you. You can see I have only a few lines for the settings I want to control.

```
[mysqld]
default-time-zone='UTC'
disable_log_bin
innodb_buffer_pool_size = 4G
innodb_log_buffer_size = 512M
innodb_log_file_size = 1G
innodb_write_io_threads = 16
innodb_flush_log_at_trx_commit = 0
innodb_doublewrite=0
sort_buffer_size = 8M
```

**Comment by huyphams** [comment]
Thanks @colonelclick for the clarification. DBngin is used for development, so we stick with the default settings (we don't want to modify any of them).

However, DBngin should mention that there is no my.cnf by default and possibly guide the user to the documentation.
